# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Taxi.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nTaxi.proto\"Z\n\x04Taxi\x12\x0f\n\x07taxi_id\x18\x01 \x01(\x03\x12\x14\n\x0c\x63onductor_id\x18\x02 \x01(\t\x12\x13\n\x0bpasajero_id\x18\x03 \x03(\t\x12\x16\n\x0e\x63osto_estimado\x18\x04 \x01(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Taxi_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TAXI._serialized_start=14
  _TAXI._serialized_end=104
# @@protoc_insertion_point(module_scope)
